#! /bin/sh
xsetroot -cursor_name left_ptr &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config border_width         4
bspc config window_gap          15
bspc config top_padding         20

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle	 false

bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true
bspc config click_to_focus          true

bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#eeeeee"
bspc config presel_feedback_color	"#5e81ac"

bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Emacs state=tiled desktop='^3' follow=on
bspc rule -a Nautilus desktop='^4' follow=on
bspc rule -a Thunderbird desktop='^5' follow=on
bspc rule -a VirtualBox desktop='^8' follow=on
bspc rule -a Slack desktop='^7' follow=on
bspc rule -a Alacritty:fzf-menu sticky=on state=floating center
bspc rule -a Peek state=floating sticky=on center

# bspc rule -a Gimp state=floating follow=on
# bspc rule -a Nautilus state=floating follow=on

xcape -e 'Shift_L=Escape' &
xmodmap $HOME/.Xmodmap &
udiskie &
xset 60 20
xss-lock -n $HOME/.scripts/dim-screen.sh -l -- $HOME/.scripts/lock.sh &
emacs &
firefox &

main_workspaces() {
    MONITOR="$1"
    bspc monitor $MONITOR -d {Code,Web,Editor,FileBrowser,Mail,Music,Chat,VirtualBox}
}

setup_monitors() {
    DETECTED_KNOWN_MONITOR=$(autorandr 2>&1 | grep "\(detected\)\f*" | cut -d " " -f1)
    # is known setup
    if [ ! -z ${DETECTED_KNOWN_MONITOR} ]; then
        (pkill polybar)&
        autorandr --change
	# is unknown setup
    else
        (pkill polybar)&
	EXTERNAL_MONITOR=$(xrandr --query | grep -E "HDMI-?[0-9]+ connected" | cut -d " " -f1)
	xrandr --output $EXTERNAL_MONITOR --auto --scale-from 1920x1080 --output $MAIN_MONITOR
    fi

    MAIN_MONITOR=$(xrandr --query | grep -E "connected primary" | cut -d " " -f1)

    pkill compton
    compton --config $HOME/.config/compton/compton.conf &
    (MONITOR=$MAIN_MONITOR polybar --reload top) &

    if [ -z ${DETECTED_KNOWN_MONITOR} ]; then
	EXTERNAL_MONITOR=$(xrandr --query | grep -E "HDMI-?[0-9]+ connected" | cut -d " " -f1)
	main_workspaces $EXTERNAL_MONITOR
        # bspc monitor $EXTERNAL_MONITOR -d 9
    else
	main_workspaces $MAIN_MONITOR
    fi

    ~/.scripts/wallpaper.sh

    if [ "$DETECTED_KNOWN_MONITOR" == "home" ]; then
	# 96: 100%, 120: 125%, 144: 150%, 168: 175%, 192: 200%
	xrandr --dpi 144
	sleep 1
    else
	xrandr --dpi 96
    fi
}

setup_monitors

bspc subscribe monitor | while read -r line; do
    case $line in
	monitor_add*|monitor_geometry*|monitor_remove*)
            setup_monitors
	    ;;
	*)
	    ;;
    esac
done
